server:
  port: 8084

spring:
  application:
    name: task-service
  cloud:
    config:
      enabled: false
    import-check:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/league_db
    username: league_admin
    password: 123pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.duru.taskservice: DEBUG
